"""Change email to phone_number

Revision ID: f128e4e89fda
Revises: 1a31ce608336
Create Date: 2024-12-08 15:40:08.702327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f128e4e89fda'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
